### ISSUE TITLE
Who is this k0tix?

### ISSUE THREAD

**Issue by KasperKivimaeki** [gcocr-ai/gcocr.ai#6]
README.md has instructions for cloning the project.
There is a URL for the repository.
The URL is https://github.com/k0tix/gcocr.ai.git.
Why isn't the URL https://github.com/gcocr-ai/gcocr.ai.git?

**Comment by juuusto** [comment]
He is one of the main developers of this project. This should be appparent from the project contributor list. I think this issue is not relevant @nousiaa

**Comment by nousiaa** [comment]
Thanks for telling us about this issue :), but yes he is THE ONE AND ONLY k0tix (at least in the scope of this project). @k0tix

**Comment by KasperKivimaeki** [comment]
What if k0tix adds a vulnerability to his own repository? 
These current instructions put us to great danger

I think we should replace the URL

**Comment by juuusto** [comment]
Current instructions are clear and the url should not be changed, since our backend relies on it

**Comment by nousiaa** [comment]
@k0tix can be trusted.

**Comment by KasperKivimaeki** [comment]
This issue is fixed in MR #7

**Comment by KasperKivimaeki** [comment]
If you don't accept my PR, then I will move to the state of anger.
